export type Lang = "en" | "es";

export const copy = {
  en: {
    nav: { game: "Game", support: "Support", press: "Press", about: "About" },
    skip: "Skip to content",
    hero: {
      tagline: "An independent game studio in Buenos Aires. We make small games with big personality.",
      cta: "Our first game",
    },
    firstGame: {
      heading: "Our first game",
      subtitle: "From broke to God",
      bullets: [
        "Tap, merge and evolve through 30 tiers",
        "Passive income: your characters work so you don't have to",
        "Offline progress: your empire keeps spinning while you sleep",
      ],
      more: "See FisuEvolution",
      badge: "Coming soon to the App Store",
    },
    how: {
      heading: "How we work",
      blocks: [
        { title: "Economies by hand", body: "Every number in our games is simulated, balanced and re-balanced until the curve feels right." },
        { title: "Culture first", body: "Our games are made of the place they come from: its humour, its slang, its economy." },
        { title: "Built for iPhone", body: "Native Swift, offline first, no accounts, no tracking." },
      ],
    },
    facts: ["Founded 2026", "Buenos Aires, Argentina", "Platform: iOS", "Contact by email"],
    game: {
      title: "FisuEvolution",
      subtitle: "From broke to God",
      what: "Tap, merge and evolve: from neighborhood hobo to God of the universe, with stops at the corner store, the delivery bike, the office and a university diploma (doesn't pay rent, but feels great).",
      featuresHeading: "Features",
      features: [
        "30 evolution tiers with your chosen career: coder, architect, doctor or lawyer",
        "Passive income: your characters work so you don't have to",
        "Absurd economy events inspired by very real chaos",
        "Special characters: from the Crypto Bro to the Tax Demon",
        "Reincarnate: every life starts faster and weirder",
        "Offline progress: your empire keeps spinning while you sleep",
      ],
      galleryHeading: "Screenshots",
      captions: ["You start with nothing", "Meet the special characters", "Choose your career", "Open chests, unlock looks", "Come back for the daily reward", "Reincarnate and start over, faster"],
      sheetHeading: "Fact sheet",
      sheet: [
        ["Genre", "merge / idle"], ["Platform", "iOS 17 or later"], ["Price", "Free, with in-app purchases"],
        ["Languages", "Spanish, English"], ["Developer", "Ader Games"], ["Release", "To be announced"],
      ],
      footerLinks: { support: "Support", privacy: "Privacy", terms: "Terms", press: "Press kit" },
    },
    about: {
      title: "About",
      paragraphs: [
        "Ader Games is an independent game studio founded in 2026 in Buenos Aires, Argentina.",
        "We are a small studio focused on iPhone games with a strong cultural identity: our games are made of the place they come from — its humour, its slang, its economy. We build them in native Swift, offline first, with no accounts and no tracking.",
        "Our first title is FisuEvolution, a merge/idle game where you evolve from neighborhood hobo to God of the universe.",
      ],
      companyHeading: "Company information",
      companyRows: { legalName: "Legal name", taxId: "Tax ID (CUIT)", address: "Registered address", email: "Contact" },
    },
    press: {
      title: "Press kit",
      boilerplateHeading: "Boilerplate",
      boilerplate: "Ader Games is an independent game studio in Buenos Aires, Argentina, founded in 2026. It makes small iPhone games with big personality — native Swift, offline first, no accounts, no tracking. Its first title is FisuEvolution, a merge/idle game about evolving from neighborhood hobo to God of the universe.",
      factsheetHeading: "Factsheet — FisuEvolution",
      assetsHeading: "Brand assets",
      assetsNote: "Don't recolour, redraw or add effects to the logo.",
      assets: [
        ["Wordmark (PNG, on black)", "/brand/logo.png"],
        ["Wordmark — flat mono (PNG)", "/brand/logo-mono.png"],
        ["Mark — the \"A\" (PNG)", "/brand/mark.png"],
        ["FisuEvolution key art (PNG)", "/fisuevolution/keyart.png"],
        ["FisuEvolution app icon (PNG)", "/fisuevolution/icon.png"],
      ],
      screenshotsHeading: "Screenshots",
      contactHeading: "Press contact",
    },
    support: {
      title: "Support — FisuEvolution",
      contactLead: "Write to us — the more detail (what you did, what you expected, what happened), the better. When reporting a bug, include your iPhone model and iOS version.",
      contactCta: "Email support",
      faqHeading: "Frequently asked questions",
      answerNote: "We answer in Spanish or English.",
    },
    legal: { updated: "Last updated", toc: "On this page" },
    notFound: { title: "Page not found", body: "That page doesn't exist. The economy, probably.", back: "Back to home" },
    footer: { noCookies: "This site uses no cookies and no analytics.", rights: "All rights reserved." },
  },
  es: {
    nav: { game: "Juego", support: "Soporte", press: "Prensa", about: "Nosotros" },
    skip: "Saltar al contenido",
    hero: {
      tagline: "Estudio independiente de videojuegos en Buenos Aires. Hacemos juegos chicos con mucha personalidad.",
      cta: "Nuestro primer juego",
    },
    firstGame: {
      heading: "Nuestro primer juego",
      subtitle: "De fisura a Dios",
      bullets: [
        "Tapeá, mergeá y evolucioná por 30 niveles",
        "Ingresos pasivos: tus personajes laburan solos",
        "Jugá offline: tu imperio sigue girando mientras dormís",
      ],
      more: "Ver FisuEvolution",
      badge: "Muy pronto en la App Store",
    },
    how: {
      heading: "Cómo trabajamos",
      blocks: [
        { title: "Economías a mano", body: "Cada número de nuestros juegos está simulado, balanceado y rebalanceado hasta que la curva se siente bien." },
        { title: "La cultura primero", body: "Nuestros juegos están hechos del lugar del que salen: su humor, su lengua, su economía." },
        { title: "Hechos para iPhone", body: "Swift nativo, primero offline, sin cuentas y sin rastreo." },
      ],
    },
    facts: ["Fundado en 2026", "Buenos Aires, Argentina", "Plataforma: iOS", "Contacto por email"],
    game: {
      title: "FisuEvolution",
      subtitle: "De fisura a Dios",
      what: "Tapeá, mergeá y evolucioná: de El Fisura del barrio a Dios del universo, con escalas en el kiosco, el delivery, la oficina y el título de la UBA (que no paga el alquiler, pero emociona).",
      featuresHeading: "Características",
      features: [
        "30 niveles de evolución con la carrera que elijas: programador, arquitecto, médico o abogado",
        "Ingresos pasivos: tus personajes laburan solos",
        "Eventos económicos absurdos inspirados en un caos muy real",
        "Personajes especiales: del Crypto Bro al Demonio de ARCA",
        "Reencarná: cada vida arranca más rápida y más absurda",
        "Jugá offline: tu imperio sigue girando mientras dormís",
      ],
      galleryHeading: "Capturas",
      captions: ["Arrancás de fisura", "Cruzate con los personajes especiales", "Elegí tu destino (con título)", "Abrí cofres y ganá pintas", "Volvé por el regalo diario", "Reencarná y arrancá más rápido"],
      sheetHeading: "Ficha técnica",
      sheet: [
        ["Género", "merge / idle"], ["Plataforma", "iOS 17 o posterior"], ["Precio", "Gratis, con compras dentro de la app"],
        ["Idiomas", "Español, Inglés"], ["Desarrollador", "Ader Games"], ["Lanzamiento", "Por anunciar"],
      ],
      footerLinks: { support: "Soporte", privacy: "Privacidad", terms: "Términos", press: "Press kit" },
    },
    about: {
      title: "Nosotros",
      paragraphs: [
        "Ader Games es un estudio independiente de videojuegos fundado en 2026 en Buenos Aires, Argentina.",
        "Somos un estudio chico enfocado en juegos de iPhone con identidad cultural fuerte: nuestros juegos están hechos del lugar del que salen — su humor, su lengua, su economía. Los hacemos en Swift nativo, primero offline, sin cuentas y sin rastreo.",
        "Nuestro primer título es FisuEvolution, un juego merge/idle donde evolucionás de El Fisura del barrio a Dios del universo.",
      ],
      companyHeading: "Información de la empresa",
      companyRows: { legalName: "Razón social", taxId: "CUIT", address: "Domicilio legal", email: "Contacto" },
    },
    press: {
      title: "Press kit",
      boilerplateHeading: "Boilerplate",
      boilerplate: "Ader Games es un estudio independiente de videojuegos de Buenos Aires, Argentina, fundado en 2026. Hace juegos chicos de iPhone con mucha personalidad — Swift nativo, primero offline, sin cuentas y sin rastreo. Su primer título es FisuEvolution, un juego merge/idle sobre evolucionar de El Fisura del barrio a Dios del universo.",
      factsheetHeading: "Factsheet — FisuEvolution",
      assetsHeading: "Assets de marca",
      assetsNote: "No recolorear, redibujar ni agregar efectos al logo.",
      assets: [
        ["Wordmark (PNG, sobre negro)", "/brand/logo.png"],
        ["Wordmark — mono plano (PNG)", "/brand/logo-mono.png"],
        ["Marca — la \"A\" (PNG)", "/brand/mark.png"],
        ["Key art FisuEvolution (PNG)", "/fisuevolution/keyart.png"],
        ["Ícono de la app (PNG)", "/fisuevolution/icon.png"],
      ],
      screenshotsHeading: "Capturas",
      contactHeading: "Contacto de prensa",
    },
    support: {
      title: "Soporte — FisuEvolution",
      contactLead: "Escribinos: cuanto más detalle (qué hiciste, qué esperabas, qué pasó), mejor. Al reportar un bug, incluí el modelo de iPhone y la versión de iOS.",
      contactCta: "Escribir a soporte",
      faqHeading: "Preguntas frecuentes",
      answerNote: "Respondemos en español o inglés.",
    },
    legal: { updated: "Última actualización", toc: "En esta página" },
    notFound: { title: "Página no encontrada", body: "Esa página no existe. La economía, seguramente.", back: "Volver al inicio" },
    footer: { noCookies: "Este sitio no usa cookies ni analytics.", rights: "All rights reserved." },
  },
} as const;
